package com.myteam.client_onboarding_enrichment;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Client implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Client() {
    }




}